server.port=8090

# Notify SDK configuration
notify.ai.properties.base-package=com.notify.ecommerce
notify.ai.properties.application-name=ecommerce-app
notify.ai.properties.client-token=eyJjbGllbnRJZCI6ImNjbG91ZC1zcHJpbmdib290LWNsaWVudC1jZGUzY2QxNy0wYjlhLTRkMTYtOTYwNC04NmFhOGMxNjE0NmEiLCJhcGlLZXkiOiIyVlBQMkVJSlYyWTNLUVM2IiwiYXBpU2VjcmV0IjoiY2ZsdFQxblFJNG9TenppYUVxUDBzS29IRTN4NExQcytoeTkzWHV2b01xTzlzcjRrRDFnZU02a2hWTjRIdC9TdyJ9
# Disable Kafka (not needed for testing)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
